### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by goldentouch74** [korado531m7/AnywhereBackpack#1]
When crafting a backpack doesnt remove leather and sometimes stuff will be deleted out of the back pack (tested on a test server only i had access to)

**Comment by goldentouch74** [comment]
Android
The craftings on all devices and cant confirm the deleting for ios/win 10

**Comment by korado531m7** [comment]
ok. thank you.
if updated, please report whether the issue is fixed

**Comment by korado531m7** [comment]
Fixed the issue. please test it.

**Comment by goldentouch74** [comment]
[Server thread/CRITICAL]: TypeError: "Return value of korado531m7\AnywhereBackpack\AnywhereBackpack::getBackpackItem() must be an instance of pocketmine\item\Item, none returned" (EXCEPTION) in "plugins/AnywhereBackpack_dev-12.phar/src/korado531m7/AnywhereBackpack/AnywhereBackpack" at line 118

**Comment by goldentouch74** [comment]
Just tested, you cant craft backpacks at all now

**Comment by korado531m7** [comment]
in 1.4.1 version is not completed.
and i just uploaded 1.4.2. please test this.
