### ISSUE TITLE
Support via multiple servers

### ISSUE THREAD

**Issue by Wertzui123** [korado531m7/AnywhereBackpack#3]
Id woud like it, when you coud have the same backpack on multiple Servers!

**Comment by korado531m7** [comment]
you mean support mysql?

**Comment by Wertzui123** [comment]
Yes

**Comment by korado531m7** [comment]
I submitted plugin on poggit that supporting mysql. please wait :)

**Comment by lowingly** [comment]
It seems that it now supports multiple server sync backpacks. Can you write a simple tutorial?@korado531m7 
 I don't understand what a database-name. Thank you.
(Database-host: xxxxx.com
Database-username: Administrator
Database-password: *******
Database-name: ?
Database-port: 10280)

**Comment by lowingly** [comment]
I just googled what is mysql, it seems that this is not a simple process, it seems that I need to build a mysql server to achieve synchronization backpack. Please ignore my previous question... I can't build mysql server. But still thank the author, this is a good plugin.   T_T
