### ISSUE TITLE
Some Errors and suggestions

### ISSUE THREAD

**Issue by Wertzui123** [korado531m7/AnywhereBackpack#5]
Hi, I found an error

When you open a backpack with /backpack 1 take some Items out and close it, then when an other player opens the backpack there are all items still there. So you can duplicate items!!!

And 1. can you add the feature, that everyone has its one backback. So you can do /backpack 2 and open you 2. backpack, and when you're friend does /backpack 2 it opens his backpack. And you would need the permission backpak.open.own to do that. With backpack.open.other you could to /backpack Alex 3 and it would open Alexes 3. Backpack. Also I would like it if you could adjust the crafting recipe in the config, and that you have a crafting permission.

I would be very happy if you would add this features and fix the bug!

**Comment by korado531m7** [comment]
thank you for repoting and suggestion.
it's really fatal and i haven't expected that because i can only test on one device.
i'll fix the issue soon.

hmm, so you mean adding friend program for backpack that allow only them to open?


k, i'll add the permission to crafting.
