### ISSUE TITLE
Bug: Cannot create item

### ISSUE THREAD

**Issue by Kauso8507** [korado531m7/AnywhereBackpack#7]
You can't craft a backpack.

**Comment by Mohagames205** [comment]
Please tell us what error you get.

**Comment by Kauso8507** [comment]
That's the problem. you get no error.

Mohamed <notifications@github.com> schrieb am Mo., 8. Juli 2019, 20:25:

**Comment by korado531m7** [comment]
did you place 8 leathers like ring on the crafting table?

**Comment by Kauso8507** [comment]
Yes. There was no item out.

mizuka792 <notifications@github.com> schrieb am Di., 9. Juli 2019, 13:18:

**Comment by korado531m7** [comment]
what the version of PocketMine do you use?

**Comment by korado531m7** [comment]
and version of this plugin?

**Comment by Kauso8507** [comment]
I use the latest version of PocketMine. And the latest plugin version of
Poggit.

mizuka792 <notifications@github.com> schrieb am Di., 9. Juli 2019, 13:38:

**Comment by Mohagames205** [comment]
Did you check if the plugin is even loading and getting enabled?
Also, is it possible that there may be conflicting plugins.

**Comment by Kauso8507** [comment]
it is loading. I also tried it on a test server without other plugins.

Mohamed <notifications@github.com> schrieb am Di., 9. Juli 2019, 13:55:

**Comment by korado531m7** [comment]
you said 'latest of pocketmine', is it stable version (not 4.0.0)?

**Comment by Kauso8507** [comment]
yes the stable

mizuka792 <notifications@github.com> schrieb am Mi., 10. Juli 2019, 00:54:

**Comment by korado531m7** [comment]
i'll debug the issue and fix it after i arrived to home.
thank you for reporting it :)

**Comment by Kauso8507** [comment]
many thanks

mizuka792 <notifications@github.com> schrieb am Mi., 10. Juli 2019, 09:26:

**Comment by korado531m7** [comment]
i checked. but there are no issues. i could make backpack chest with leather.

**Comment by Kauso8507** [comment]
lol I test it again in the evening

mizuka792 <notifications@github.com> schrieb am Mi., 10. Juli 2019, 13:04:

**Comment by thnuder** [comment]
I am getting this error on running the server
[Server thread/ERROR]: Could not load plugin 'AnywhereBackpack': plugin exists
also when listing plugins the AnywhereBackpack in red
